name: FirstPlugin
version: '1.0-SNAPSHOT'
main: firstplugin.firstplugin.FirstPlugin
api-version: '1.18'
commands:
  fly:
    description: Toggles flying for the command sender.
    usage: /fly
    aliases: [f, flying, togglefly]
    permission: fly
    permission-message: You do not have permission.
  menu:
    description: Opens the game menu.
    usage: /menu
    
